homeassistant:
  name: Home
  latitude: 43.7
  longitude: -79.4
  elevation: 76
  unit_system: metric
  time_zone: America/Toronto
  http:
  use_x_forwarded_for: true trusted_proxies:
  - 10.0.0.0/8
  ssl_profile: intermediate
  trusted_hosts:
    https://homeassistant-3avi.onrender.com/
  mqtt:
  broker: mqtt
  port: 8123
  external_url: https://homeassistant-3avi.onrender.com/
  
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/8
  server_host: 0.0.0.0
  # Force Home Assistant to treat traffic as HTTPS even behind the proxy
  ssl_profile: intermediate
  trusted_hosts:
    https://homeassistant-3avi.onrender.com/
